# Generated by Django 3.1.3 on 2021-01-25 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0003_auto_20210124_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
    ]
